spring.application.name=employee-directory
server.port=${PORT:8080}
spring.datasource.url=jdbc:h2:mem:proddb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
management.endpoints.web.exposure.include=health,info
